<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
        <?php $this->printLayoutHead(); ?>
        <link rel="stylesheet" href="/amember/application/default/views/public/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/style.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/resposive.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/black.css">
        <link rel="SHORTCUT ICON" HREF="images/logo.png">
    </head>
    <body<?php if (!empty($body_class)): ?> class="<?php p($body_class) ?>"<?php endif; ?>>
        <?php echo $this->placeholder('body-start'); ?>
        <!--<div id="notificationModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-logo">
                            <img src="/amember/application/default/views/public/images/blacklogo.png" alt="">
                        </div>
                    </div>
                    <div class="modal-body">
                        <p>
                            "Working Disc Jockey's" defined as those who are playing music in a Lounge, Bar, Club, or on the Radio (FM, AM, Satellite or internet), or in the Mobile Entertainment environment.
                        </p>
                        <p>
                            8thwonderpromos.com provides a service to the working DJ, and the content on this website is made aviable under permission granted by the original copyright holders and/or their consigns under usage and display definitions in accordance with United States Copyright Code, title 17; 106(4,5) and 114(b) respectively, and for use in ASCAP, BMI and SESAC compliant venues.
                        </p>
                        <p>
                            8thwonderpromos is for "Working Disc Jockey's" ONLY. Its is not an mp3 or mp4 audio and or video consumer resource. The content on this website is ONLY to be made available to DJ's, NOT the general public under any circumstance or condition. By pressing "I agree to these terms" below you certify that you are a Disc Jockey or Disc Jockey Company.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default agree" data-dismiss="modal">I, Agree</button>
                        <button type="button" href="javascript:close_window();" class="btn btn-primary decline">Decline</button>
                    </div>
                </div>
            </div>
        </div>-->
        <div id="layout-wrapper">
            <header>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-2">
                            <a href="#" class="logo" title="8thWonder"><img src="/amember/application/default/views/public/images/logo.png" alt=""></a>
                        </div>
                        <div class="col-sm-7">
                            <div class="top-nav-holder">
                                <div class="navbar navbar-inverse">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                    <div class="collapse navbar-collapse" id="miller-navbar">
                                        <ul class="nav navbar-nav">
                                            <li class="current-menu-item"><a href="https://www.8thwonderpromos.com" title="Home">Home</a></li>
                                            <li><a href="https://pool.8thwonderpromos.com" title="Pool">Pool</a></li>
                                            <li><a href="javascript:void(0);" title="Store">Store</a></li>
                                            <li><a href="https://pool.8thwonderpromos.com/contact" title="Contact">Contact</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <?php $user = Am_Di::getInstance()->auth->getUser(); ?>
                            <?php if ($user && empty($this->noUserIdentityBlock)) : ?>
                                <a href="https://www.8thwonderpromos.com/amember/logout" class="home_login">Logout(<?php echo $user->login; ?>)</a> 
                            <?php else: ?>
                                <a href="https://www.8thwonderpromos.com/amember/signup" title="Join For Free" class="join-fr-free">Join For Free</a>				
                                <a href="https://www.8thwonderpromos.com/amember/login" title="Login" class="home_login">Login</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <a class="blk-wht-circle">
                    <span class="black-hemi"><img src="/amember/application/default/views/public/images/black-hemisphere.png" alt=""></span>
                    <span class="white-hemi"><img src="/amember/application/default/views/public/images/white-hemisphere.png" alt=""></span>
                </a>
            </header>
            <section id="playlist-tabs">
                <div class="container">
                    <?php include $this->_script('_content.phtml'); ?>
                </div>
            </section>
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <ul class="footer-nav">
                                <li class="current-menu-item"><a href="https://www.8thwonderpromos.com" title="Home">Home</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/" title="Pool">Pool</a></li>
                                <li><a href="javascript:void(0);" title="Store">Store</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/contact" title="Contact">Contact</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/crate" title="Crate">Crate</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <a href="#" title="8thWonder" class="ftr-logo"><img src="/amember/application/default/views/public/images/blacklogo.png" alt=""></a>
                            <p class="cpyryt">&copy; <script type="text/javascript">var today = new Date();
                                document.write(today.getFullYear());</script> 8th Wonder Promos. All Rights Reserved</p>
                            <ul class="social-icons">
                                <li><a href="#" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Youtube"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul class="otherlink">
                                <li class="current-menu-item"><a href="https://pool.8thwonderpromos.com/terms" title="Terms">Terms</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/privacy" title="Privacy">Privacy</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/copyright" title="Copyright">Copyright</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/faq" title="F.A.Q">F.A.Q</a></li>
                                <li><a href="https://pool.8thwonderpromos.com/feedback" title="Feedback">Feedback</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <?php echo $this->placeholder('body-finish'); ?>
        <script src="https://codeorigin.jquery.com/jquery-1.10.2.min.js" data-cookieconsent="necessary"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script type="text/javascript">
            (function ($) {
                'use strict';
                $(document).on('show.bs.tab', '.nav-tabs-responsive [data-toggle="tab"]', function (e) {
                    var $target = $(e.target);
                    var $tabs = $target.closest('.nav-tabs-responsive');
                    var $current = $target.closest('li');
                    var $parent = $current.closest('li.dropdown');
                    $current = $parent.length > 0 ? $parent : $current;
                    var $next = $current.next();
                    var $prev = $current.prev();
                    var updateDropdownMenu = function ($el, position) {
                        $el.find('.dropdown-menu')
                            .removeClass('pull-xs-left pull-xs-center pull-xs-right')
                            .addClass('pull-xs-' + position);
                    };

                    $tabs.find('>li').removeClass('next prev');
                    $prev.addClass('prev');
                    $next.addClass('next');

                    updateDropdownMenu($prev, 'left');
                    updateDropdownMenu($current, 'center');
                    updateDropdownMenu($next, 'right');
                });
                $(document).on("click", ".decline", function () {
                    window.close();
                    var objWindow = window.open(location.href, "_self");
                    objWindow.close();
                });
            })(jQuery);
            $(window).on('load', function () {
                $("#notificationModal").modal({show: true, backdrop: false});
            });
        </script>
    </body>
</html>