<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
    <!--<![endif]-->

    <head>
        <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->printLayoutHead(); ?>
        <link rel="stylesheet" href="/amember/application/default/views/public/css/bootstrap.min.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/animations.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/fonts.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/cue.css">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/main.css" class="color-switcher-link">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/shop.css" class="color-switcher-link">
        <link rel="stylesheet" href="/amember/application/default/views/public/css/mediaelementplayer-legacy.css">
        <script src="/amember/application/default/views/public/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body<?php if (!empty($body_class)): ?> class="<?php p($body_class) ?>"<?php endif; ?>>
        <?php echo $this->placeholder('body-start'); ?>
        <div id="canvas">
            <div id="box_wrapper">
                <section class="page_topline ds table_section table_section_md">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4 col-sm-6 text-center text-md-left">
                                <div class="inline-content medium">
                                    <p> <i class="fa fa-phone highlight rightpadding_5" aria-hidden="true"></i> 1833 DJ Promo </p>
                                    <p class="greylinks"> <i class="fa fa-envelope highlight rightpadding_5" aria-hidden="true"></i> <a href="mailto:support@8thwonderpromos.com">support@8thwonderpromos.com</a> </p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-6 text-center text-md-center"> 
                                <a class="social-icon socicon-facebook" href="#" title="Facebook"></a> 
                                <a class="social-icon socicon-twitter" href="#" title="Twitter"></a> 
                                <a class="social-icon socicon-google" href="#" title="Google"></a> 
                                <a class="social-icon socicon-linkedin" title="Linked In"></a>
                            </div>
                        </div>
                    </div>
                </section>
                <header class="page_header header_white toggler_xs_right tall_header">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-12 display_table">
                                <div class="header_left_logo display_table_cell"> <a href="./" class="logo top_logo">
                                        <img src="http://pool.8thwonderpromos.com/images/logo.png" width="130" height="100" alt="">
                                    </a> </div>
                                <div class="header_mainmenu display_table_cell text-center">
                                    <!-- main nav start -->
                                    <nav class="mainmenu_wrapper">
                                        <ul class="mainmenu nav sf-menu">
                                            <li class="active"> 
                                                <a href="/">Home</a>
                                            </li>
                                            <li> <a href="http://pool.8thwonderpromos.com">Pool</a>
                                                <ul>
                                                    <li> 
                                                        <a href="http://pool.8thwonderpromos.com">Recordpool</a>
                                                    </li>
                                                    <li> <a href="http://pool.8thwonderpromos.com/trending">Trending</a> </li>
                                                    <li> <a href="http://pool.8thwonderpromos.com/browse">Browse</a> </li>
                                                    <li> <a href="http://pool.8thwonderpromos.com/login">Pool Login</a> </li>
                                                </ul>
                                            </li>
                                            <li><a href="javascript:void(0);">Store</a></li>
                                            <li> <a href="http://pool.8thwonderpromos.com/contact">Contacts</a></li>
                                        </ul>
                                    </nav>
                                    <span class="toggle_menu"><span></span></span>
                                </div>
                                <div class="header_right_buttons display_table_cell text-right hidden-xs"> 
                                    <?php $user = Am_Di::getInstance()->auth->getUser(); ?>
                                    <?php if ($user && empty($this->noUserIdentityBlock)) : ?>
                                        <a href="https://www.8thwonderpromos.com/amember/logout" class="theme_button color1">Logout(<?php echo $user->login; ?>)</a> 
                                    <?php else: ?>
                                        <a href="https://www.8thwonderpromos.com/amember/login" class="theme_button color1">Sign In</a> 
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </header>
                <section id="latest-album" class="ls ms section_padding_top_50 columns_margin_bottom_30 columns_padding_25">
                    <div class="container">
                        <?php include $this->_script('_content.phtml'); ?>
                    </div>
                </section>
                <footer class="page_footer ds section_padding_top_100 section_padding_bottom_75">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4 text-center">
                                <div class="widget widget_text"> <img src="http://pool.8thwonderpromos.com/images/logo.png" alt="">
                                        <!--<p class="topmargin_20">You can purchase our pool membership, where you will find all our content.</p>-->
                                    <div class="topmargin_25"> <a href="#" class="social-icon border-icon rounded-icon socicon-apple"></a> <a href="#" class="social-icon border-icon rounded-icon socicon-play"></a> <a href="#" class="social-icon border-icon rounded-icon socicon-amazon"></a> <a href="#" class="social-icon border-icon rounded-icon socicon-spotify"></a>									<a href="#" class="social-icon border-icon rounded-icon socicon-soundcloud"></a> </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-6 text-center">
<!--                                <div class="widget widget_text">
                                    <h4 class="widget-title"> Contact Form </h4>
                                    <form class="contact-form" method="post" action="./">
                                        <div class="bottommargin_10"> <label for="name-footer">Your Name <span class="required">*</span></label> <input type="text" aria-required="true" size="30" value="" name="name" id="name-footer" class="form-control text-center" placeholder="Full Name*"> </div>
                                        <div class="bottommargin_10">
                                            <label for="message-footer">Message</label> <textarea aria-required="true" rows="3" cols="45" name="message" id="message-footer" class="form-control text-center" placeholder="Message..."></textarea> </div>
                                        <div class="contact-form-submit topmargin_10">
                                            <button type="submit" id="contact_form_submit_footer" name="contact_submit" class="theme_button color1">Send Message</button> </div>
                                    </form>
                                </div>-->
                            </div>
                            <div class="col-md-4 col-sm-6 text-center">
                                <div class="widget widget_text">
                                    <h4 class="widget-title"> My Contacts </h4>
                                    <div>
                                        <div class="media small-media inline-block">
                                            <div class="media-left"> <i class="fa fa-map-marker highlight" aria-hidden="true"></i> </div>
                                            <div class="media-body"> 1767 Central Park Ave Suite 381 Yonkers NY 10710 </div>
                                        </div>
                                        <div class="media small-media inline-block">
                                            <div class="media-left"> <i class="fa fa-phone highlight" aria-hidden="true"></i> </div>
                                            <div class="media-body"> 1833 DJ Promo </div>
                                        </div>
                                        <div class="media small-media inline-block">
                                            <div class="media-left"> <i class="fa fa-print highlight" aria-hidden="true"></i> </div>
                                            <div class="media-body"> 1767 Central Park Ave Suite 381 Yonkers NY 10710 </div>
                                        </div>
                                        <div class="media small-media greylinks inline-block">
                                            <div class="media-left"> <i class="fa fa-envelope highlight" aria-hidden="true"></i> </div>
                                            <div class="media-body"> <a href="mailto:support@8thwonderpromos.com">support@8thwonderpromos.com</a> </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <section class="ls page_copyright section_padding_top_40 section_padding_bottom_40">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 text-center">
                                <div class="bottommargin_10"> <a class="social-icon socicon-facebook" href="#" title="Facebook"></a> <a class="social-icon socicon-twitter" href="#" title="Twitter"></a> <a class="social-icon socicon-youtube" href="#" title="Youtube"></a> <a class="social-icon socicon-google"
                                                                                                                                                                                                        href="#" title="Google"></a> </div>
                                <p class="small-text">&copy; Copyright 2018. All Rights Reserved.</p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php echo $this->placeholder('body-finish'); ?>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="/amember/application/default/views/public/js/main.js"></script>
    </body>
</html>